### ISSUE TITLE
Erro ao Adicionar novo campo no checkout

### ISSUE THREAD

**Issue by Marusso** [elisei/advanced-fields-checkout#1]
Olá, 

Estou tentando adicionar um novo campo no checkout utilizando a opção "Opção avançadas dos campos do checkout" porem ao adicionar, recebo a seguinte mensagem

![image](https://user-images.githubusercontent.com/16608158/152585148-59f029ad-5f2e-4239-8bc3-af37a9d4f517.png)

Alguém saberia me dizer o que seria?

**Comment by elisei** [comment]
Olá @Marusso  tudo bem?

Recomendo olhar como esse novo campo foi criado, aqui está as condições para ele ser carregado com sucesso:

Se for de "customer"
https://github.com/elisei/advanced-fields-checkout/blob/Magento%402.4/Block/Adminhtml/Form/Field/Column/FieldColumn.php#L137-L143

Se for de "customer_address"
https://github.com/elisei/advanced-fields-checkout/blob/Magento%402.4/Block/Adminhtml/Form/Field/Column/FieldColumn.php#L155-L161

**Comment by Marusso** [comment]
Olá @elisei 

Obrigado pelo retorno.

Estava verificando o atributo e ele esta como is_visible = 1

Para maior referencia do atributo que estou falando, é do módulo System Code Brazil Customer

https://github.com/m2-systemcode/BrazilCustomerAttributes/blob/master/Setup/InstallData.php

**Comment by elisei** [comment]
Olá @Marusso 

Nesse caso precisa ver diretamente com eles!

Mas apenas uma dica, esse módulo não é necessário. https://github.com/elisei/tax-document-validation-br
